### ISSUE TITLE
Unable to generate POT with Python3

### ISSUE THREAD

**Issue by rffontenelle** [gnome-keysign/gnome-keysign#20]
Following [keysign/locale/README.rst](https://github.com/gnome-keysign/gnome-keysign/blob/master/keysign/locale/README.rst), I'm unable to generate the POT file with Python3 (`python` binary), as can be seen below. I'm running on Arch Linux 64-bit, Python 3.6.2

Interesting enough, this issue DOES NOT happen with Python2.

See error output:
```
$ python setup.py extract_messages
running extract_messages
extracting messages from keysign/GPGQRCode.py
extracting messages from keysign/GtkKeyserver.py
extracting messages from keysign/KeyPresent.py
extracting messages from keysign/Keyserver.py
extracting messages from keysign/QRCode.py
extracting messages from keysign/__init__.py
extracting messages from keysign/__main__.py
extracting messages from keysign/_version.py
extracting messages from keysign/app.py
extracting messages from keysign/app.ui
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    'test': NoseTestCommand,
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/rffontenelle/repos/gnome-keysign/.eggs/Babel-2.5.1-py3.6.egg/babel/messages/frontend.py", line 467, in run
    for filename, lineno, message, comments, context in extracted:
  File "/home/rffontenelle/repos/gnome-keysign/.eggs/Babel-2.5.1-py3.6.egg/babel/messages/extract.py", line 157, in extract_from_dir
    dirpath=absname,
  File "/home/rffontenelle/repos/gnome-keysign/.eggs/Babel-2.5.1-py3.6.egg/babel/messages/extract.py", line 212, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/home/rffontenelle/repos/gnome-keysign/.eggs/Babel-2.5.1-py3.6.egg/babel/messages/extract.py", line 241, in extract_from_file
    strip_comment_tags))
  File "/home/rffontenelle/repos/gnome-keysign/.eggs/Babel-2.5.1-py3.6.egg/babel/messages/extract.py", line 320, in extract
    options=options or {})
  File "/home/rffontenelle/repos/gnome-keysign/babelglade/__init__.py", line 108, in extract_glade
    parser = GladeParser(fileobj)
  File "/home/rffontenelle/repos/gnome-keysign/babelglade/__init__.py", line 24, in __init__
    parser.returns_unicode = True
AttributeError: returns_unicode
```

**Comment by muelli** [comment]
Good catch.
It seems [the property is gone](https://docs.python.org/2/library/pyexpat.html#xml.parsers.expat.xmlparser.returns_unicode) in Python 3.

Can you try the following:
```
parser = expat.ParserCreate('utf-8')
```

**Comment by rffontenelle** [comment]
I'm not sure where should i put the line you asked me, but I put it in [`babelglade/__init__.py` line 22](https://github.com/gnome-keysign/gnome-keysign/blob/master/babelglade/__init__.py#L22) and it didn't work.

**Comment by RyuzakiKK** [comment]
The Pull Request that I created few seconds ago should fix this issue. I tested it on Arch with both Python 2 and 3.

**Comment by rffontenelle** [comment]
Thanks, @RyuzakiKK. Works for me too.
