### ISSUE TITLE
Crash if we try to sign with a private key without its master key

### ISSUE THREAD

**Issue by RyuzakiKK** [gnome-keysign/gnome-keysign#51]
If we create a subkey like described here https://wiki.debian.org/Subkeys and we try to use it in keysign, we will face a crash because the related master key is not available in the keyring.

This is the traceback of the error:
```
Traceback (most recent call last):
  File "/tmp/gnome-keysign/keysign/receive.py", line 155, in
on_sign_key_confirmed
    sign_keydata_and_send(keydata))
  File "/tmp/gnome-keysign/keysign/util.py", line 127, in
sign_keydata_and_send
    for uid, encrypted_key in list(sign_keydata_and_encrypt(keydata,
error_cb)):
  File "/tmp/gnome-keysign/keysign/gpgmeh.py", line 418, in
sign_keydata_and_encrypt
    ctx.interact(key, GenEdit(sign_key(error_cb=error_cb)).edit_cb,
sink=sink)
  File "/usr/lib/python3.6/site-packages/gpg/core.py", line 853, in
interact
    gpgme.gpg_raise_callback_exception(self)
  File "/usr/lib/python3.6/site-packages/gpg/gpgme.py", line 3495, in
gpg_raise_callback_exception
    return _gpgme.gpg_raise_callback_exception(arg1)
  File "/tmp/gnome-keysign/keysign/gpgmeh.py", line 78, in edit_cb
    data = self.generator.send((status, args)) #, sinkdata))
  File "/tmp/gnome-keysign/keysign/gpgmeh.py", line 151, in sign_key
    raise RuntimeError("Error signing key: %s" % prompt)
RuntimeError: Error signing key: keysig 67108881
```

A test for this issue has been created here  https://github.com/RyuzakiKK/gnome-keysign/commit/6cce91cc4fc21427addf986dc5ebf15415b3069b

**Comment by RyuzakiKK** [comment]
Fixed with de41e69. Now we filter out keys with an unusable offline master key.
