### ISSUE TITLE
Programming error has been detected (kali linux)

### ISSUE THREAD

**Issue by zelionx** [gnome-keysign/gnome-keysign#56]
```python
System information: Linux-4.16.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Python information: 2.7.15 (default, May  1 2018, 05:55:50) 
[GCC 7.3.0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/keysign/app.py", line 152, on_activate(self=<app.KeysignApp object at 0x7fb65bda1fa0 (keysign+app+KeysignApp at 0x55bc9a03b290)>, app=<app.KeysignApp object at 0x7fb65bda1fa0 (keysign+app+KeysignApp at 0x55bc9a03b290)>)
            # Load Receive part
            self.receive = PswMappingReceiveApp(self.on_presign_mapped)
            rs = self.receive.stack
  File "/usr/lib/python2.7/dist-packages/keysign/app.py", line 83, __init__(self=<keysign.app.PswMappingReceiveApp instance>, mapped_func=<bound method KeysignApp.on_presign_mapped of <a...1fa0 (keysign+app+KeysignApp at 0x55bc9a03b290)>>, builder=None)
            # ReceiveApp, in Python 2, is an old style object
            ReceiveApp.__init__(self, builder=builder)
            self.func = mapped_func
  variables: {'self': ('local', <keysign.app.PswMappingReceiveApp instance at 0x7fb64a369440>), 'builder': ('local', None), 'ReceiveApp.__init__': ('global', <unbound method ReceiveApp.__init__>)}
  File "/usr/lib/python2.7/dist-packages/keysign/receive.py", line 104, __init__(self=<keysign.app.PswMappingReceiveApp instance>, builder=<Gtk.Builder object at 0x7fb64cad1b40 (GtkBuilder at 0x55bc9ae3b850)>)
            self.discovery = AvahiKeysignDiscoveryWithMac()
            ib = builder.get_object('infobar_discovery')
  variables: {'AvahiKeysignDiscoveryWithMac': ('global', <class 'keysign.avahidiscovery.AvahiKeysignDiscoveryWithMac'>), 'self.discovery': ('local', <keysign.app.PswMappingReceiveApp instance at 0x7fb64a369440>)}
  File "/usr/lib/python2.7/dist-packages/keysign/avahidiscovery.py", line 68, __init__(self=<avahidiscovery.AvahiKeysignDiscoveryWithMac obj...+AvahiKeysignDiscoveryWithMac at 0x55bc9ac09780)>, *args=(), **kwargs={})
            avahi_service_type = '_gnome-keysign._tcp'
            self.avahi_browser = AvahiBrowser(service=avahi_service_type)
            self.avahi_browser.connect('new_service', self.on_new_service)
  File "/usr/lib/python2.7/dist-packages/keysign/network/AvahiBrowser.py", line 86, __init__(self=<AvahiBrowser.AvahiBrowser object at 0x7fb64cad1...ork+AvahiBrowser+AvahiBrowser at 0x55bc9ac022a0)>, loop=None, service='_gnome-keysign._tcp')
            self.server = dbus.Interface( self.bus.get_object(avahi.DBUS_NAME, '/'),
                    'org.freedesktop.Avahi.Server')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, get_object(self=<dbus._dbus.SystemBus (system)>, bus_name='org.freedesktop.Avahi', object_path='/', introspect=True, follow_name_owner_changes=False, **kwargs={})
                                         introspect=introspect,
                                         follow_name_owner_changes=follow_name_owner_changes)
  variables: {'follow_name_owner_changes': ('local', False)}
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, __init__(self=<ProxyObject wrapping <dbus._dbus.SystemBus (system) at 0x7fb64cd3c530> org.freedesktop.Avahi />, conn=<dbus._dbus.SystemBus (system)>, bus_name='org.freedesktop.Avahi', object_path='/', introspect=True, follow_name_owner_changes=False, **kwargs={})
            if not follow_name_owner_changes:
                self._named_service = conn.activate_name_owner(bus_name)
  variables: {'bus_name': ('local', 'org.freedesktop.Avahi'), 'self._named_service': ('local', 'org.freedesktop.Avahi'), 'conn.activate_name_owner': ('local', <bound method SystemBus.activate_name_owner of <dbus._dbus.SystemBus (system) at 0x7fb64cd3c530>>)}
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, activate_name_owner(self=<dbus._dbus.SystemBus (system)>, bus_name='org.freedesktop.Avahi')
                    # else it doesn't exist: try to start it
                    self.start_service_by_name(bus_name)
                    return self.get_name_owner(bus_name)
  variables: {'self.start_service_by_name': ('local', <bound method SystemBus.start_service_by_name of <dbus._dbus.SystemBus (system) at 0x7fb64cd3c530>>), 'bus_name': ('local', 'org.freedesktop.Avahi')}
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, start_service_by_name(self=<dbus._dbus.SystemBus (system)>, bus_name='org.freedesktop.Avahi', flags=0)
                                             'StartServiceByName',
                                             'su', (bus_name, flags)))
  variables: {'bus_name': ('local', 'org.freedesktop.Avahi'), 'flags': ('local', 0)}
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, call_blocking(self=<dbus._dbus.SystemBus (system)>, bus_name='org.freedesktop.DBus', object_path='/org/freedesktop/DBus', dbus_interface='org.freedesktop.DBus', method='StartServiceByName', signature='su', args=('org.freedesktop.Avahi', 0), timeout=-1.0, byte_arrays=False, **kwargs={})
            reply_message = self.send_message_with_reply_and_block(
                message, timeout)

Can anyone help me out? Thanks

**Comment by RyuzakiKK** [comment]
It seems like that the application is unable to start the avahi service.
Open a terminal and write:
`systemctl status avahi-daemon`
What's the output?

Also, how did you install gnome-keysign?

**Comment by zelionx** [comment]
Hey Ryuzaki, i did all your commands, the first command "systemctl status avahi-daemon" is saying that the service is inactive (dead), the second command said "Failed to start avahi.service: Unit avahi.service not found."
Do i need to install avahi service?

**Comment by zelionx** [comment]
Oh and i installed by with terminal, i typed `apt search gnome` and found `gnome-keysign/kali-rolling,now 0.9.7.2-1 a`, i installed it, and done

**Comment by RyuzakiKK** [comment]
Yes avahi is a required dependency.
You can find the dependency list in the README.md file.

With `apt install gnome-keysign` you can install keysign with all the
needed dependendency.

**Comment by zelionx** [comment]
Hey, i typed `apt install gnome-keysign` and it is saying
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnome-keysign is already the newest version (0.9.7.2-1).
`
What should i do?

**Comment by RyuzakiKK** [comment]
I just saw your second reply. That's strange then cause avahi should be listed as a dependency, so apt should have installed it for you.
If you do `dpkg -s avahi` does it say that is installed or not?

**Comment by zelionx** [comment]
It's saying that is not installed

**Comment by RyuzakiKK** [comment]
I just realized that I wrongly wrote the start command, can you try `sudo systemctl start avahi-daemon.service` ?

**Comment by zelionx** [comment]
Yup, that command worked, thank you so much!

**Comment by RyuzakiKK** [comment]
This is an issue also present with Arch linux.
I should gracefully handle this case displaying a pop up informing the user about what went wrong and which command he needs to issue in order to start avahi.

Thanks for reporting it.
