### ISSUE TITLE
BarcodeReaderGTK

### ISSUE THREAD

**Issue by rdibble1986** [gnome-keysign/gnome-keysign#58]
#### Description
```python
System information: Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
Python information: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/keysign/scan_barcode.py", line 148, on_unmap(self=<scan_barcode.BarcodeReaderGTK object at 0x7f3f6...scan_barcode+BarcodeReaderGTK at 0x55dcfac00ef0)>, *args=(<scan_barcode.BarcodeReaderGTK object at 0x7f3f6...scan_barcode+BarcodeReaderGTK at 0x55dcfac00ef0)>,), **kwargs={})
            e.g. when the tab of a notebook has changed'''
            self.pipeline.set_state(Gst.State.PAUSED)
            # Actually, we stop the thing for real
AttributeError: 'BarcodeReaderGTK' object has no attribute 'pipeline'
```

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
System information: Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
Python information: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/keysign/scan_barcode.py", line 148, on_unmap(self=<scan_barcode.BarcodeReaderGTK object at 0x7f3f6...scan_barcode+BarcodeReaderGTK at 0x55dcfac00ef0)>, *args=(<scan_barcode.BarcodeReaderGTK object at 0x7f3f6...scan_barcode+BarcodeReaderGTK at 0x55dcfac00ef0)>,), **kwargs={})
            e.g. when the tab of a notebook has changed'''
            self.pipeline.set_state(Gst.State.PAUSED)
            # Actually, we stop the thing for real
AttributeError: 'BarcodeReaderGTK' object has no attribute 'pipeline'
```

**Comment by muelli** [comment]
How did you install the software?

Do you have a camera?

Does `gst-launch-1.0 autovideosrc ! queue ! videoconvert ! gtksink` work for you, e.g. give you your camera feed?

**Comment by muelli** [comment]
closing due to inactivity. Please reopen with the requested information.
