### ISSUE TITLE
Not receiving

### ISSUE THREAD

**Issue by Sudhik** [gnome-keysign/gnome-keysign#99]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
System information: Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
Python information: 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/keysign/scan_barcode.py", line 142, on_map(self=<scan_barcode.BarcodeReaderGTK object at 0x7f834...scan_barcode+BarcodeReaderGTK at 0x562619b61f50)>, *args=(<scan_barcode.BarcodeReaderGTK object at 0x7f834...scan_barcode+BarcodeReaderGTK at 0x562619b61f50)>,), **kwargs={})
            '''It seems this is called when the widget is becoming visible'''
            self.run()
  variables: {'self.run': ('local', <bound method BarcodeReaderGTK.run of <scan_barcode.BarcodeReaderGTK object at 0x7f834dd28910 (keysign+scan_barcode+BarcodeReaderGTK at 0x562619b61f50)>>)}
  File "/usr/lib/python2.7/dist-packages/keysign/scan_barcode.py", line 113, run(self=<scan_barcode.BarcodeReaderGTK object at 0x7f834...scan_barcode+BarcodeReaderGTK at 0x562619b61f50)>)
            log.info("Launching pipeline %s", pipeline)
            pipeline = Gst.parse_launch(pipeline)
  variables: {'pipeline': ('local', 'autovideosrc  \n ! tee name=t \n       t. ! queue ! videoconvert \n                  ! zbar cache=true attach_frame=true \n                  ! fakesink \n       t. ! queue ! videoconvert \n                 ! gtksink sync=false name=imagesink enable-last-sample=false \n'), 'Gst.parse_launch': ('global', gi.FunctionInfo(parse_launch))}
Error: gst_parse_error: no element "gtksink" (1)
```

**Comment by muelli** [comment]
Thanks for reaching out!
It looks like gstreamer dependencies are missing.
How have you installed the app?
